language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
cache:
  apt: true
addons:
  postgresql: "9.3"
install:
  - pip install -U .
before_script:
  - pip install psycopg2cffi
  - psql -U postgres -c "CREATE DATABASE pq_test"
script:  python setup.py test
